pragma Singleton

import QtQml
import org.kde.kirigami as Kirigami

// Internal theme-configuration singleton.
//
// Do NOT edit this file to configure the theme -- edit ThemeUserConfig.qml.
//
// This wraps ThemeUserConfig so that:
//   * the values are loaded natively by the QML engine (no file IO, no
//     XMLHttpRequest, no QML_XHR_ALLOW_FILE_READ env var, no INI parser);
//   * a default is still applied if the user deletes a property, so a
//     half-edited config file can never produce `undefined` toggles.
QtObject {
    id: themeConfig

    // The single user-editable config object.
    readonly property ThemeUserConfig _user: ThemeUserConfig {}

    // Coerce to bool with a fallback: covers a missing/deleted property.
    function _bool(x, def) {
        return (x === undefined || x === null) ? def : !!x;
    }

    // Resolved font family: the user's value, or the system default font
    // when the user left it blank (or deleted the property).
    readonly property string fontFamily: {
        const f = _user.fontFamily;
        return (f === undefined || f === null || String(f).trim() === "")
            ? Kirigami.Theme.defaultFont.family
            : f;
    }

    readonly property bool showClock:
        _bool(_user.showClock, true)
    readonly property bool showClockOnlyWhenUiVisible:
        _bool(_user.showClockOnlyWhenUiVisible, false)
    readonly property bool showLayoutLabel:
        _bool(_user.showLayoutLabel, false)
    readonly property bool showUserImage:
        _bool(_user.showUserImage, true)
    readonly property bool showMediaControls:
        _bool(_user.showMediaControls, true)
}
